# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
# SPDX-FileCopyrightText: 2026 Callan Barrett

[toolchain]
channel    = "1.90.0"
components = ["rustfmt", "clippy"]
targets    = ["armv7-unknown-linux-gnueabihf"]
profile    = "minimal"
